# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
# This file uses maven resource filtering to fill in values at compile time
main: com.example.groupid.samplebukkitplugin.SampleBukkitPlugin
name: ${project.name}
version: ${project.version}
author: ExampleAuthor
description: ${project.description}
commands:
  sample:
    description: set the sample message
    usage: /<command> [message]
    permission: sample.message
permissions:
  sample.*:
    description: gives all permissions of the SamplePlugin
    default: op
    children:
      sample.message:
        description: gives permission to set the sample message using the sample command